### ISSUE TITLE
error in rowmeans

### ISSUE THREAD

**Issue by Phylloxera** [eMetaboHUB/MS-CleanR#10]
Hi,

I think I have a similar issue to #1 
Do you have any guidance on which filter(s) to try singly to see if any features remain after cleaning?

Thanks!

**Comment by guikool** [comment]
1. Check if your data have MS/MS since all feature without MS/MS are discarded
2. Don't forget to tick some adducts behind M-H and M+H in MSdial adduct tab, since if this is the only adduct detected, it may conduct to an error.
3. Check your data arrangement: discard "-" for instance in sample or class naming. Same sample and order should be respected if you perform pos and neg mode

**Comment by guikool** [comment]
We also noticed an issue with RSD filter in some cases
Try to untick rsd filter and rerun the filtering process
